### ISSUE TITLE
Cookies Issue.

### ISSUE THREAD

**Issue by Xentimus** [jabbey1/UGDownloader#1]
Hello! There is a cookies issue right now when trying to download the tabs. You can bypass it by quickly accepting the cookies. I tried using your previous code and adding an extension to chrome (I don't care about cookies) by adding this line:

c_options.add_extension(
    ex_path + r'\\idcac-3.4.6.crx')

where ex_path = the path of the program and by downloading the extension as a crx.

Can you add it on the updated program, or by auto-accepting the cookies so it works better? 
Or if you can upload the new source files, it would be awesome!
Thank you very much!

**Comment by jabbey1** [comment]
Hey thanks for bringing this up. Just uploaded the new source files.
Haven't made your fix yet though, can't reproduce it on my end. Can you
download the .crx in the program or do you have to manually add it?
Thanks- Jake

**Comment by jabbey1** [comment]
To clarify, the problem is a popup asking you to accept cookies, correct? If not, possibly the uncommenting this line would help:
# "profile.managed_default_content_settings.cookies": 2,

**Comment by Xentimus** [comment]
I'm new to python so I just tried to fix it on my end, and thought that loading an extension to block cookies would be a nice idea, but I just have to add the crx manually on the folder of the program for now! 

The popup is about privacy, not cookies as I thought at first, I managed to take a screenshot:

![image](https://user-images.githubusercontent.com/46158206/231677453-3be37ae0-172d-4f32-b1ab-47608777e8f9.png)

I will try this line too to see if it works! Thank you!;

**Comment by jabbey1** [comment]
You might want to try the latest source code. I've included the mentioned lines, but on my end it doesn't make any difference whether I include them or not so I'm wondering how they would impact you

**Comment by Xentimus** [comment]
I will check everything! Thank you! I think that pop up is because we are in EU, where GDPR and cookies are mandatory, while probably you are in the US? I will come back to you when I check it! Thank you for your work!!

**Comment by Xentimus** [comment]
Option 1 does not stop the popup, unfortunately.. I still keep using the extension option by adding the path to it!

**Comment by jabbey1** [comment]
Yup, in the U.S. so that makes sense. Bummer it doesn't work- I'll have to mess with it more to see if I can get it to show up. I was having problems getting the extension to work in my code but I didn't work on it too long

**Comment by Xentimus** [comment]
I made it work with this line:     c_options.add_extension(str(Path.cwd()) + r'\\_UGDownloaderFiles\\extension_3_4_6_0.crx')
The line you had was checking in the temp directory of chrome or something i think!

**Comment by jabbey1** [comment]
Ah I see- you can't use extensions while running chrome headless. Maybe at some point I'll add a checkbox that loads up the extension while disabling headless. Anyways, glad it's running for you!

**Comment by jabbey1** [comment]
Try the latest code- added a checkbox in the GUI to load the extension

**Comment by Xentimus** [comment]
Oh nice thank you! Yes I was trying it only without being headless, because I wante to check where it stops! There is also a way to add Powertabs and blocked tabs if you want to do this too (but I don't know if UG will like the blocked tabs method).

**Comment by jabbey1** [comment]
Yeah I saw sawyersteven had the blocked tabs in his fork. I hadn't personally run into an issue of wanting to download a blocked tab (I could just be downloading weird artists) so it wasn't really on my radar. Powertabs I might add at some point too, again I don't use them so I wasn't paying much attention to them

**Comment by Xentimus** [comment]
Thanks for your work!
