### ISSUE TITLE
Multiple Artist Songs

### ISSUE THREAD

**Issue by Rexadev** [jabbey1/UGDownloader#12]
1. How to enter it's name in UGDownloader
2. How to download it when batch downloading artist
3. UG also has `feat.` `&` `,`

![image](https://github.com/jabbey1/UGDownloader/assets/62152714/a0785866-8dea-4ecc-a3ea-573856e5d709)

![image](https://github.com/jabbey1/UGDownloader/assets/62152714/883d5d60-aad3-4824-8e3b-c797a21c2ff7)

**Comment by jabbey1** [comment]
Hmm, a lot of these edge cases actually are handled already. It may not be practical to cover the very rare ones.

**Comment by Rexadev** [comment]
> a lot of these edge cases actually are handled already.

How ?



Also, most non-rock/metal music have collaborations

**Comment by jabbey1** [comment]
In my testing some cases were covered by how the program works already. If you're curious how you can do your own testing. Chasing down every naming convention is not worth it as there isn't much standardization to how artists can be named on UG, and you can always just go download the ones you want anyways.
