### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by Rexadev** [jabbey1/UGDownloader#13]
1. Move Notes to a `i` button near the logo
2. Remove the top bar
3. Add the icon next to the Program Name
![image](https://github.com/jabbey1/UGDownloader/assets/62152714/c46a4126-3efa-45ee-bbe2-5f1979616330)
4. Remove the Exit button there is already X button
![image](https://github.com/jabbey1/UGDownloader/assets/62152714/b165a2de-f7da-451f-8aa0-4748ec90bd39)
5. Move this to a settings Menu Along with Theme Menu
![image](https://github.com/jabbey1/UGDownloader/assets/62152714/8f976747-9cb5-47ff-8fce-28fc61e9cc89)
![image](https://github.com/jabbey1/UGDownloader/assets/62152714/44256fbc-a892-40f0-bf6b-65ef8b733fe2)
6. Move this to top and rearrange the buttons
![image](https://github.com/jabbey1/UGDownloader/assets/62152714/a7c3e82b-902d-49f1-967a-6a6b751ec898)
![image](https://github.com/jabbey1/UGDownloader/assets/62152714/09b7df4a-8044-4058-80eb-1834065dfa41)

**Comment by jabbey1** [comment]
Tweaked GUI. Some changes resembled what you had going at the end. The other stuff I'm not really interested in changing.

**Comment by Rexadev** [comment]
@jabbey1 New UI is weirder, it's too tall
