### ISSUE TITLE
Downloading of mp3 backing tracks?

### ISSUE THREAD

**Issue by JPHFanedits** [jabbey1/UGDownloader#5]
this isn't so much an issue as it is a request. Is it possible to add to this the ability to download the mp3's of the individual instruments from pro or official tabs? if you view the page source for any pro or official tab, you can find the mp3 link and download it by highlighting the address and saving as. But if this could just download all mp3 files from the source that would be awesome

**Comment by jabbey1** [comment]
With a lot of rewriting it may be able to, but that would probably violate their terms of service which isn't really a road I want to cross, sorry.

**Comment by jabbey1** [comment]
With a lot of rewriting it may be able to, but that would probably violate their terms of service which isn't really a road I want to cross, sorry.
