### ISSUE TITLE
I can't download the tab, I'm getting an error

### ISSUE THREAD

**Issue by erdo62-62** [jabbey1/UGDownloader#6]
GetHandleVerifier [0x0042A813+48355]
        (No symbol) [0x003BC4B1]
        (No symbol) [0x002C5358]
        (No symbol) [0x002E61AC]
        (No symbol) [0x002E1EF3]
        (No symbol) [0x002E0579]
        (No symbol) [0x00310C55]
        (No symbol) [0x0031093C]
        (No symbol) [0x0030A536]
        (No symbol) [0x002E82DC]
        (No symbol) [0x002E93DD]
        GetHandleVerifier [0x0068AABD+2539405]
        GetHandleVerifier [0x006CA78F+2800735]
        GetHandleVerifier [0x006C456C+2775612]
        GetHandleVerifier [0x004B51E0+616112]
        (No symbol) [0x003C5F8C]
        (No symbol) [0x003C2328]
        (No symbol) [0x003C240B]
        (No symbol) [0x003B4FF7]
        BaseThreadInitThunk [0x75B07BA9+25]
        RtlInitializeExceptionChain [0x774ABD2B+107]
        RtlClearBits [0x774ABCAF+191]

![Ekran görüntüsü 2024-02-08 235036](https://github.com/jabbey1/UGDownloader/assets/158849853/7d597ab5-8016-4734-94f7-1022d691febf)

**Comment by jabbey1** [comment]
What's the text above what you pasted?
I'd update Chrome and restart it before trying anything else.
Also, you can't search for individual tabs. It's meant to get everything available for a certain artist. So, your search would be for 'Metallica'. It needs to be properly capitalized as well.

**Comment by erdo62-62** [comment]
I wrote the same thing, "Metallica" is updated in Chrome, I am encountering the same error again, I wonder what I am doing wrong?

**Comment by jabbey1** [comment]
I meant can you paste the error message above Backtrace? That might help. It looks like it's a problem with Chrome. You could try Firefox as well. You could also try with the 'run in background' unchecked.

**Comment by erdo62-62** [comment]
I tried hard but I couldn't succeed. Thank you

**Comment by erdo62-62** [comment]
It worked ok :)  official tabs not downloading

**Comment by erdo62-62** [comment]
Can you write code to download official tabs as "gp" file?

**Comment by jabbey1** [comment]
Sorry, it's just for Guitar Pro files.
